[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "dating-ai-dashboard"
source = "."

[services.variables]
VITE_API_BASE_URL = "https://mcp-api-server-production.up.railway.app"
VITE_WS_URL = "wss://mcp-websocket-server.up.railway.app"
VITE_DEBUG_MODE = "false"
