[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
startCommand = "/docker-entrypoint.sh"

[[services]]
name = "dating-ai-dashboard"
source = "."

[services.variables]
VITE_API_BASE_URL = "https://mcp-api-server-production.up.railway.app"
VITE_WS_URL = "wss://n8n-workflows-production.up.railway.app"
VITE_DEBUG_MODE = "false"
VITE_ENVIRONMENT = "production"
NODE_ENV = "production"
